### ISSUE TITLE
There is a red vertical line when scale down the timeline

### ISSUE THREAD

**Issue by YiniXu9506** [GopherJ/Vs#6]
Firstly, thank you for offering such a good component!

I found there might be some bugs in this component. I use d3-timeline in Summary.vue

<img width="706" alt="screen shot 2018-08-19 at 6 59 42 pm" src="https://user-images.githubusercontent.com/34967660/44308135-285e3880-a3e2-11e8-8419-7e94b19dd6b6.png">
<img width="345" alt="screen shot 2018-08-19 at 6 59 55 pm" src="https://user-images.githubusercontent.com/34967660/44308136-2e541980-a3e2-11e8-88b2-3361f084276b.png">

It seems everything looks good here
<img width="1269" alt="screen shot 2018-08-19 at 7 01 06 pm" src="https://user-images.githubusercontent.com/34967660/44308147-53488c80-a3e2-11e8-9461-a973c0dda7af.png">

but when I scale down enough, I found a vertical red line showing in the graph.
<img width="1267" alt="screen shot 2018-08-19 at 7 01 15 pm" src="https://user-images.githubusercontent.com/34967660/44308157-770bd280-a3e2-11e8-8260-df5a18d3463a.png">

Do you have any idea about this situation? Let me know if you figure out what is going on. Appreciate!

**Comment by GopherJ** [comment]
Let me see that. It's strange

**Comment by GopherJ** [comment]
And also a question is the what's the value of  `currentTimeLineWidth` in options ?

**Comment by YiniXu9506** [comment]
Hello, Jiang! Thank you for your replying. The version of Vs is 0.6.8.

Yes. There is `currentTimeLineWidth` in my options, and I set it as 100. It works perfectly when I set the value to 1. Thank you so much

I have another question for you. Can I define the color of the bar by myself? The api `className` does change the color, but I still want to define it by myself.

**Comment by GopherJ** [comment]
Yes normally you can define your own className, here we have some examples: 
```css
 .d3-timeline .entry--interval--default {
        fill:#896bda;
        stroke: #896bda;
        stroke-opacity: 1;
        cursor: pointer;
    }
    .d3-timeline .entry--point--default {
        fill:#896bda;
        stroke: #896bda;
        stroke-opacity: 1;
        cursor: pointer;
    }
```

You can define your own class like this, but pay attention that the class you've defined shouldn't be put in VueJs scoped style because the component is rendered dynamically. 

You can define your own class like this:
```css
<style>
.yourCssClass {
    fill: 'xxx',
   stroke: 'xxx'
}
</style>
```
and then in your data: 

```javascript
[
  {
     ....
     className: 'yourCssClass'
   }
]
```
